### ISSUE TITLE
Unified Numbering Issue

### ISSUE THREAD

**Issue by TheFrommie86** [trolley813/dv-rolling-stock-numbering#5]
When using the "Unified Numbering" Setting and using the value 1 instead of giving trains the IDs 001 it does the opposite and dets the ID to 1000 

Issue was already with Version 1.1.0 but unly since the B99

**Comment by trolley813** [comment]
What's your min and max range?

**Comment by TheFrommie86** [comment]
both were set to 1

**Comment by trolley813** [comment]
Oh, then you essentially limited the pool of available numbers to a single value of 1. So you run out of numbers when even placing a 2nd engine of the same type, and the game starts assigning numbers from 1000 (this is expected behaviour when the available numbers are exhausted, it's actually the same as in the base game).

If you want the numbers to be assigned in the range e.g. 1 to 500, set min = 1 and max = 500.

**Comment by TheFrommie86** [comment]
I also tried Min = = and Max = 1 game Issue

**Comment by TheFrommie86** [comment]
> Oh, then you essentially limited the pool of available numbers to a single value of 1. So you run out of numbers when even placing a 2nd engine of the same type, and the game starts assigning numbers from 1000 (this is expected behaviour when the available numbers are exhausted, it's actually the same as in the base game).
> 
> If you want the numbers to be assigned in the range e.g. 1 to 500, set min = 1 and max = 500.

Ah okay I see so instead of setting the Min and Max to the same value I should use a slightly wider range to ensure all Trains that Pawn in the Area (When Used Model Based Prefix) whill have the Chance to spawn.
I guess you can Mark it as resolved then (Both here and on Nexus)
